---
# Playbook to set up folder structure for new project

- name: Prompt for project/folder name
  hosts: localhost

  vars_prompt:
    - name: project_name
      prompt: Enter the name of Project/Folder?
      private: no

  tasks:

  - name: Create Inventory Folder
    file:
      path: "{{ destination_directory }}/{{ project_name }}/inventory"
      state: directory
    delegate_to: localhost
    
  - name: Create Project Directory and Group Vars Folder
    file:
      path: "{{ destination_directory }}/{{ project_name }}/group_vars"
      state: directory
    delegate_to: localhost

  - name: Create Roles Folder
    file:
      path: "{{ destination_directory }}/{{ project_name }}/roles"
      state: directory
    delegate_to: localhost

  - name: Copy ansible.cfg
    copy:
      src: "{{ source_directory }}/ansible.cfg"
      dest: "{{ destination_directory }}/{{ project_name }}/ansible.cfg"
    delegate_to: localhost

  - name: Copy sample_playbook.yml
    copy:
      src: "{{ source_directory }}/sample_playbook.yml"
      dest: "{{ destination_directory }}/{{ project_name }}/sample_playbook.yml"
    delegate_to: localhost

  - name: Copy sample hosts file
    copy:
      src: "{{ source_directory }}/inventory/"
      dest: "{{ destination_directory }}/{{ project_name }}/inventory/"
    delegate_to: localhost

  - name: Copy group_vars file
    copy:
      src: "{{ source_directory }}/group_vars/"
      dest: "{{ destination_directory }}/{{ project_name }}/group_vars/"
    delegate_to: localhost

  - name: Copy roles file
    copy:
      src: "{{ source_directory }}/roles/"
      dest: "{{ destination_directory }}/{{ project_name }}/roles/"
    delegate_to: localhost

