---
- name: Find Wi-Fi interface names starting with 'w'
  hosts: localhost
  tasks:
    - name: Get Wi-Fi interface status
      command: "ip link show eth0"
      register: interface_status
    - name: Display interface status
      debug:
        var: interface_status.stdout

