---
- name: Find Wi-Fi interface names starting with 'w'
  hosts: homeserver
  become: true

  tasks:
    - name: Check if the user exists
      shell: "pveum user list | grep -i shajal@pam"
      register: check_user
      changed_when: false

    - name: Debug pveum user
      debug:
        msg: "{{ check_user }}"
