---
- name: Setup after new install
  hosts: homeserver
  gather_facts: true
  become: yes

  roles:
    - update_repo
    - wifi_setup
    - create_sudo_user
    - generate_ssh_localhost
    - basics

