---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts["interfaces"]

- name: Extract interfaces starting with 'w'
  set_fact:
    wifi_interfaces: "{{ ansible_facts['interfaces'] | select('match', '^w.*') | list }}"

- name: Set the first Wi-Fi interface or empty string
  set_fact:
    primary_wifi_interface: "{{ wifi_interfaces[0] if wifi_interfaces | length > 0 else '' }}"

- name: Fail if no Wi-Fi interface found
  fail:
    msg: "No Wi-Fi interface found to configure."
  when: primary_wifi_interface == ''

- name: Bring the Wi-Fi interface up
  command: "ip link set {{ primary_wifi_interface }} up"
  when: primary_wifi_interface != ''

- name: Generate WPA configuration using wpa_passphrase
  shell: "wpa_passphrase '{{ ssid }}' '{{ passphrase }}' > /etc/wpa_supplicant/wpa_supplicant.conf"
  args:
    creates: /etc/wpa_supplicant.conf

- name: Start wpa_supplicant service
  shell: "wpa_supplicant -B -i {{ primary_wifi_interface }} -c /etc/wpa_supplicant/wpa_supplicant.conf"

- name: Obtain an IP address via DHCP
  shell: "dhclient {{ primary_wifi_interface }}"

- name: Verify Wi-Fi connection
  command: "ping -c 3 8.8.8.8"
  register: ping_result
  ignore_errors: yes

- name: Display connection status
  debug:
    msg: "{{ 'Wi-Fi connected successfully!' if ping_result.rc == 0 else 'Failed to connect to Wi-Fi.' }}"

- name: Remove existing configurations for wlo1 from /etc/network/interfaces
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^iface {{ primary_wifi_interface }}'
    state: absent

- name: To be able to auto connect to WiFi and assign static ip we need to edit /etc/network/interfaces
  template:
    src: templates/network_interface.j2
    dest: /etc/network/interfaces

- name: To be able to auto connect to WiFi, we need to configure /etc/systemd/system/wpa_supplicant.service
  template:
    src: templates/wpa_supplicant_service.j2
    dest: /etc/systemd/system/wpa_supplicant.service

- name: Enable wpa_supplicant
  service:
    name: wpa_supplicant
    enabled: yes

- name: Restart wpa_supplicant
  service:
    name: wpa_supplicant
    state: restarted

- name: Restart the networking service
  service:
    name: networking
    state: restarted

- name: Sleep for few seconds
  pause:
    seconds: 15


