---
- name: Copy web_supplicant deb files with dependencies
  copy:
    src: "../files/"
    dest: "/tmp/"

- name: Install deb packages
  apt:
    deb:
      - "../files/libnl-genl-3-200_3.7.0-0.2+b1_amd64.deb"
      - "../files/libpcsclite1_1.9.9-2_amd64.deb"
      - "../files/wpasupplicant_2.10-12+deb12u2_amd64.deb"