---

- name: Check if the user exists
  shell: "pveum user list | grep -q {{ username }}"
  register: check_user
  ignore_errors: true
  changed_when: false

- name: "Add Proxmox User account (1/4)"
  command: "pveum useradd {{ username  }}@pam -comment 'New admin user'"
  when: check_user.rc != 0

- name: "Add Proxmox User account (2/4)" 
  command: "pveum groupadd {{ proxmox_new_group }} -comment 'Local Administrator'"
  when: check_user.rc != 0

- name: "Add Proxmox User account (3/4)"
  command: "pveum aclmod / -group {{ proxmox_new_group }} -role Administrator"
  when: check_user.rc != 0

- name: "Add Proxmox User account (4/4)"
  command: "pveum usermod {{ username }}@pam -group {{ proxmox_new_group }}"
  when: check_user.rc != 0
