---
- name: "Add Proxmox User account (1/4)"
  command: "pveum useradd {{ username  }}@pam -comment 'New admin user'"

- name: "Add Proxmox User account (2/4)" 
  command: "pveum groupadd {{ proxmox_new_group }} -comment 'Local Administrator'"

- name: "Add Proxmox User account (3/4)"
  command: "pveum aclmod / -group {{ proxmox_new_group }} -role Administrator"

- name: "Add Proxmox User account (4/4)"
  command: "pveum usermod {{ username }}@pam -group {{ proxmox_new_group }}"
