---
- name: Install sudo
  apt:
    name: sudo
    state: presentS

- name: Create new user
  user:
    name: "{{ proxmox_username }}"
    password: "{{ proxmox_username | password_hash('sha512') }}"
    groups:
      - sudo
      - users
    append: true
    shell: "{{ shell }}"
    update_password: on_create

- name: Enable passwordless sudo for "{{ proxmox_username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ proxmox_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Suppress login message (hushlogin)
  file:
    path: "/home/{{ proxmox_username }}/.hushlogin"
    mode: 0644
    owner: "{{ proxmox_username }}"
    group: "{{ proxmox_username }}"
    modification_time: preserve
    access_time: preserve
    state: touch